#!/usr/bin/env python3
"""
Hướng dẫn lấy Telegram API ID và API Hash
"""

print("🔗 HƯỚNG DẪN LẤY TELEGRAM API")
print("=" * 50)
print()
print("1. Mở trình duyệt và truy cập: https://my.telegram.org/auth")
print("2. Nhập số điện thoại Telegram của bạn (ví dụ: +84944300848)")
print("3. Nhấn 'Next'")
print("4. Mở Telegram trên điện thoại/máy tính")
print("5. Bạn sẽ nhận được mã xác nhận trong Telegram")
print("6. Nhập mã xác nhận vào website")
print("7. Sau khi đăng nhập thành công:")
print("   - Nhấn vào 'API development tools'")
print("   - Hoặc truy cập trực tiếp: https://my.telegram.org/apps")
print()
print("8. Tạo ứng dụng mới:")
print("   App title: SoDEX Bot")
print("   Short name: sodex_bot") 
print("   URL: (để trống)")
print("   Platform: Desktop")
print("   Description: Auto verify referral codes")
print()
print("9. Nhấn 'Create application'")
print()
print("10. Sao chép thông tin:")
print("    api_id: (một số, ví dụ: 12345678)")
print("    api_hash: (chuỗi 32 ký tự, ví dụ: abc123...)")
print()
print("11. Cập nhật file .env:")
print("    TELEGRAM_API_ID=12345678")
print("    TELEGRAM_API_HASH=abc123def456789012345678901234ab")
print()
print("🔴 LƯU Ý QUAN TRỌNG:")
print("- API ID là SỐ, không có chữ")
print("- API Hash là chuỗi 32 ký tự")
print("- KHÔNG phải Bot Token!")
print()
input("Nhấn Enter để mở website...")

import webbrowser
webbrowser.open('https://my.telegram.org/auth')
